<a href="https://colab.research.google.com/github/ranjiiit/Housing_Rent-Dataset-Noida/blob/main/Linear_algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#importing library
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [6]:
data = pd.read_csv('/content/House_Rent_Dataset_Noida.csv')
data

,Rent Price,Rent Details,Rent Title,Rent location,Rent Caption
0,"₹ 30,000",3 BHK - 2 Bathroom - 1800 sqft,well lighted by sunlight airy good view,"Noida, Uttar Pradesh",well lighted by sunlight airy good view
1,"₹ 5,000",2 BHK - 2 Bathroom - 1000 sqft,2BHK flat for sharing,"Sector 104, Noida",2BHK flat for sharing
2,"₹ 15,000",2 BHK - 2 Bathroom - 1300 sqft,1 private room available in 2bhk flat..,"Noida, Uttar Pradesh",1 private room available in 2bhk flat..
3,"₹ 28,000",2 BHK - 2 Bathroom - 1200 sqft,2bhk rent furnished,"Sector 104, Noida",2bhk rent furnished
4,"₹ 10,000",1 BHK - 1 Bathroom - 200 sqft,1 RK Available for Rent,"Sector 104, Noida",1 RK Available for Rent
...,...,...,...,...,...
9995,"₹ 30,000",2 BHK - 2 Bathroom - 800 sqft,2bhk full furnished,NaN,eliteListingBadge
9996,"₹ 4,000",1 BHK - 1 Bathroom - 1275 sqft,Room on Rent for Bachelors only,"Sector 20, Faridabad",NaN
9997,"₹ 8,500",2 BHK - 2 Bathroom - 0 sqft,Flatemate required.,"Shakarpur, Delhi",NaN
9998,"₹ 6,000",1 BHK - 1 Bathroom - 350 sqft,This is 1 room bucha set in East azad nagar gu...,"Azad Nagar, Delhi",NaN
9999,"₹ 13,000",1 BHK - 1 Bathroom - 360 sqft,1 BHK flat for rent,"Vasundhara Sector 3, Ghaziabad",NaN

In [7]:
data.head(10)

,Rent Price,Rent Details,Rent Title,Rent location,Rent Caption
0,"₹ 30,000",3 BHK - 2 Bathroom - 1800 sqft,well lighted by sunlight airy good view,"Noida, Uttar Pradesh",well lighted by sunlight airy good view
1,"₹ 5,000",2 BHK - 2 Bathroom - 1000 sqft,2BHK flat for sharing,"Sector 104, Noida",2BHK flat for sharing
2,"₹ 15,000",2 BHK - 2 Bathroom - 1300 sqft,1 private room available in 2bhk flat..,"Noida, Uttar Pradesh",1 private room available in 2bhk flat..
3,"₹ 28,000",2 BHK - 2 Bathroom - 1200 sqft,2bhk rent furnished,"Sector 104, Noida",2bhk rent furnished
4,"₹ 10,000",1 BHK - 1 Bathroom - 200 sqft,1 RK Available for Rent,"Sector 104, Noida",1 RK Available for Rent
5,"₹ 21,000",2 BHK - 2 Bathroom - 1000 sqft,2 bhk Galaxy Appartment,"Sector 104, Noida",2 bhk Galaxy Appartment
6,"₹ 22,000",2 BHK - 2 Bathroom - 950 sqft,Prime location Luxury flat,"Sector 104, Noida",Prime location Luxury flat
7,"₹ 22,000",2 BHK - 2 Bathroom - 950 sqft,Limite time dealocation best near metro statio...,"Sector 104, Noida",Limite time dealocation best near metro statio...
8,"₹ 20,000",2 BHK - 2 Bathroom - 1050 sqft,1Bhk/2bhk/3Bhk Flat For Rent Noida,"Sector 104, Noida",NaN
9,"₹ 9,000",2 BHK - 2 Bathroom - 120 sqft,One flatmate required must be IT professional,"Hajipur, Noida",NaN

In [8]:
data.columns

Index(['Rent Price', 'Rent Details', 'Rent Title', 'Rent location',
       'Rent Caption'],
      dtype='object')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rent Price     10000 non-null  object
 1   Rent Details   9785 non-null   object
 2   Rent Title     10000 non-null  object
 3   Rent location  8257 non-null   object
 4   Rent Caption   3368 non-null   object
dtypes: object(5)
memory usage: 390.8+ KB

In [10]:
data.isnull().sum()

Rent Price          0
Rent Details      215
Rent Title          0
Rent location    1743
Rent Caption     6632
dtype: int64

In [ ]:
data.describe()

,Rent Price,Rent Details,Rent Title,Rent location,Rent Caption
count,1593,1593,1593,1593,1593
unique,210,475,1363,462,1076
top,"₹ 15,000",2 BHK - 2 Bathroom - 700 sqft,Available 2BHK Society Flat,"Chattarpur, Delhi",Verified info pill
freq,85,64,29,112,391

In [11]:
data['Price'] = data['Rent Price'].astype(str).str.replace('₹', '', regex=False)
data['Price'] = data['Price'].str.replace(',', '', regex=False).str.strip().astype(float)

In [12]:
data['BHK'] = data['Rent Details'].str.extract(r'(\d+)\s*BHK').astype(float)

In [14]:
data['Bathroom'] = data['Rent Details'].str.extract(r'(\d+)\s*Bathroom').astype(float)

In [15]:
data['Sqft'] = data['Rent Details'].str.extract(r'(\d+)\s*sqft').astype(float)

In [16]:
data_clean = data.dropna(subset=['Price', 'BHK', 'Bathroom', 'Sqft'])
data_clean

,Rent Price,Rent Details,Rent Title,Rent location,Rent Caption,Price,BHK,Bathroom,Sqft
0,"₹ 30,000",3 BHK - 2 Bathroom - 1800 sqft,well lighted by sunlight airy good view,"Noida, Uttar Pradesh",well lighted by sunlight airy good view,30000.0,3.0,2.0,1800.0
1,"₹ 5,000",2 BHK - 2 Bathroom - 1000 sqft,2BHK flat for sharing,"Sector 104, Noida",2BHK flat for sharing,5000.0,2.0,2.0,1000.0
2,"₹ 15,000",2 BHK - 2 Bathroom - 1300 sqft,1 private room available in 2bhk flat..,"Noida, Uttar Pradesh",1 private room available in 2bhk flat..,15000.0,2.0,2.0,1300.0
3,"₹ 28,000",2 BHK - 2 Bathroom - 1200 sqft,2bhk rent furnished,"Sector 104, Noida",2bhk rent furnished,28000.0,2.0,2.0,1200.0
4,"₹ 10,000",1 BHK - 1 Bathroom - 200 sqft,1 RK Available for Rent,"Sector 104, Noida",1 RK Available for Rent,10000.0,1.0,1.0,200.0
...,...,...,...,...,...,...,...,...,...
9995,"₹ 30,000",2 BHK - 2 Bathroom - 800 sqft,2bhk full furnished,NaN,eliteListingBadge,30000.0,2.0,2.0,800.0
9996,"₹ 4,000",1 BHK - 1 Bathroom - 1275 sqft,Room on Rent for Bachelors only,"Sector 20, Faridabad",NaN,4000.0,1.0,1.0,1275.0
9997,"₹ 8,500",2 BHK - 2 Bathroom - 0 sqft,Flatemate required.,"Shakarpur, Delhi",NaN,8500.0,2.0,2.0,0.0
9998,"₹ 6,000",1 BHK - 1 Bathroom - 350 sqft,This is 1 room bucha set in East azad nagar gu...,"Azad Nagar, Delhi",NaN,6000.0,1.0,1.0,350.0
9999,"₹ 13,000",1 BHK - 1 Bathroom - 360 sqft,1 BHK flat for rent,"Vasundhara Sector 3, Ghaziabad",NaN,13000.0,1.0,1.0,360.0

In [17]:
data_clean = data_clean[(data_clean['Price'] >= 2000) & (data_clean['Price'] <= 150000)]

In [18]:
data_clean = data_clean[(data_clean['Sqft'] >= 100) & (data_clean['Sqft'] <= 6000)]

In [19]:
data_clean.columns

Index(['Rent Price', 'Rent Details', 'Rent Title', 'Rent location',
       'Rent Caption', 'Price', 'BHK', 'Bathroom', 'Sqft'],
      dtype='object')

In [20]:
X = data_clean[['BHK','Bathroom', 'Sqft']]
y = data_clean['Price']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
model= LinearRegression()

In [23]:
model.fit(X_train, y_train)

LinearRegression()

In [24]:
y_pred = model.predict(X_test)

In [25]:
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

In [26]:
print(f" Model Accuracy (R2 Score): {r2:.2f}")
print(f" Average Error (RMSE): ₹ {rmse:,.2f}")

 Model Accuracy (R2 Score): 0.38
 Average Error (RMSE): ₹ 8,824.83

In [27]:
import joblib

In [30]:
joblib.dump(model, 'model.pkl')
print("Model saved successfully as rental_model.pkl!")

Model saved successfully as rental_model.pkl!